version: "3.8"

services:
  app:
    build: ./.container/workspace
    volumes:
      - ./backend:/workspace
      - ./frontend:/workspace/frontend
      - vendor-store:/workspace/vendor
      - node_modules-store:/workspace/frontend/node_modules
    ports:
      - 8080:8080

  nginx:
    image: nginx:1.18-alpine
    ports:
      - 9000:80
    volumes:
      - ./backend:/workspace
      - ./.container/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /workspace

  db:
    build: ./.container/mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
  vendor-store:
  node_modules-store: