version: "3.8"

services:
  app:
    build: ./.container/workspace
    volumes:
      - ./server:/workspace
      - vendor-store:/workspace/vendor

  nginx:
    image: nginx:1.18-alpine
    ports:
      - 80:80
    volumes:
      - ./server:/workspace
      - ./.container/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /workspace

  db:
    build: ./.container/mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
  vendor-store: